version: "3.9"
   
services:
  db:
    image: mongo
    container_name: mongo
    volumes:
      - ./data/db:/data/db
    environment:
      -MONGO_INITDB_ROOT_USERNAME: mongo
      -MONGO_INITDB_ROOT_PASSWORD: mongo
      -MONGO_INITDB_DATABASE: mongodb_docker
    ports:
      - "27017:27017"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      -MONGO_INITDB_ROOT_USERNAME: mongo
      -MONGO_INITDB_ROOT_PASSWORD: mongo
      -MONGO_INITDB_DATABASE: mongodb_docker
    depends_on:
      - db